dist: trusty
sudo: false
group: travis_latest
language: c++
cache: ccache

env:
  global:
  - COMPILER=g++

addons:
  apt:
    sources: &apt_sources
      - ubuntu-toolchain-r-test
      - llvm-toolchain-precise-3.5
      - llvm-toolchain-precise-3.6
      - llvm-toolchain-precise-3.7
      - llvm-toolchain-precise-3.8
      - llvm-toolchain-trusty-3.9
      - llvm-toolchain-trusty-4.0
      - llvm-toolchain-trusty-5.0

compiler: clang
os: linux

matrix:
  fast_finish: true
  include:
    - env: COMPILER=g++-5
      compiler: gcc
      addons: &gcc5
        apt:
          packages: ["g++-5", "python3-pip", "lcov"]
          sources: *apt_sources

    - env: COMPILER=g++-6
      compiler: gcc
      addons: &gcc6
        apt:
          packages: ["g++-6", "python3-pip", "lcov"]
          sources: *apt_sources

    - env: COMPILER=g++-7
      compiler: gcc
      addons: &gcc7
        apt:
          packages: ["g++-7", "python3-pip", "lcov"]
          sources: *apt_sources

    - env: COMPILER=clang++-3.5
      compiler: clang
      addons: &clang35
        apt:
          packages: ["clang-3.5", "g++-7", "python3-pip", "lcov"]
          sources: *apt_sources

    - env: COMPILER=clang++-3.6
      compiler: clang
      addons: &clang36
        apt:
          packages: ["clang-3.6", "g++-7", "python3-pip", "lcov"]
          sources: *apt_sources

    - env: COMPILER=clang++-3.7
      compiler: clang
      addons: &clang37
        apt:
          packages: ["clang-3.7", "g++-7", "python3-pip", "lcov"]
          sources: *apt_sources

    - env: COMPILER=clang++-3.8
      compiler: clang
      addons: &clang38
        apt:
          packages: ["clang-3.8", "g++-7", "python3-pip", "lcov"]
          sources: *apt_sources

    - env: COMPILER=clang++-3.9
      compiler: clang
      addons: &clang39
        apt:
          packages: ["clang-3.9", "g++-7", "python3-pip", "lcov"]
          sources: *apt_sources

    - env: COMPILER=clang++-4.0
      compiler: clang
      addons: &clang40
        apt:
          packages: ["clang-4.0", "g++-7", "python3-pip", "lcov"]
          sources: *apt_sources

    - env: COMPILER=clang++-5.0
      compiler: clang
      addons: &clang50
        apt:
          packages: ["clang-5.0", "g++-7", "python3-pip", "lcov"]
          sources: *apt_sources

script:
  - export CXX=$COMPILER
  - mkdir build && cd build
  - cmake -G "Unix Makefiles" -DGSL_LITE_OPT_BUILD_TESTS=ON -DGSL_LITE_OPT_BUILD_EXAMPLES=ON .. && cmake --build . && ctest
